// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ToMEHelper")>]
[<assembly: AssemblyProductAttribute("ToMEHelper")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-12-15T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","6885376fbefb5698b6cb520246ef28a698146c6d")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ToMEHelper"
    let [<Literal>] AssemblyProduct = "ToMEHelper"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-12-15T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "6885376fbefb5698b6cb520246ef28a698146c6d"
