// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ToMEHelper.Tests")>]
[<assembly: AssemblyProductAttribute("ToMEHelper")>]
[<assembly: AssemblyVersionAttribute("0.1.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-12-16T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.2")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","09c89ffd4c332a90e2de206f17d014e990ec7b88")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ToMEHelper.Tests"
    let [<Literal>] AssemblyProduct = "ToMEHelper"
    let [<Literal>] AssemblyVersion = "0.1.2"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-12-16T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.1.2"
    let [<Literal>] AssemblyInformationalVersion = "0.1.2"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "09c89ffd4c332a90e2de206f17d014e990ec7b88"
